version: '3.8'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: develop_investree_mysql
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME:-strapi}
      MYSQL_USER: ${DATABASE_USERNAME:-strapi-user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-InvestreeDb123}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - develop_network


volumes:
  mysql_data:
    driver: local

networks:
  develop_network:
    external: true
